spring.datasource.url=jdbc:oracle:thin:@//172.17.0.120:1521/apolo
spring.datasource.username=DBO_CCM_PESSOAS
spring.datasource.password=dbo_ccm_pessoas
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


# hibernate / jpa
##spring.jpa.database-platform=org.hibernate.dialect.OracleLegacyDialect
spring.jpa.database-platform=org.hibernate.community.dialect.OracleLegacyDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

spring.jackson.deserialization.fail-on-unknown-properties=false

